// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-QSIoyFLrbaYQiKNk3GzfrG9G8b8hjbM',
    appId: '1:461843801975:web:YOUR_WEB_APP_ID_HERE',
    messagingSenderId: '461843801975',
    projectId: 'kinkprod-5f88d',
    authDomain: 'kinkprod-5f88d.firebaseapp.com',
    storageBucket: 'kinkprod-5f88d.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-QSIoyFLrbaYQiKNk3GzfrG9G8b8hjbM',
    appId: '1:461843801975:android:6e1ec875e6cdb7f51d2372',
    messagingSenderId: '461843801975',
    projectId: 'kinkprod-5f88d',
    storageBucket: 'kinkprod-5f88d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrPRvHBfzLMKGki6ajzzK7Lw3T4SSRMI',
    appId: '1:461843801975:ios:9b3f8a104b08be131d2372',
    messagingSenderId: '461843801975',
    projectId: 'kinkprod-5f88d',
    storageBucket: 'kinkprod-5f88d.firebasestorage.app',
    iosBundleId: 'com.brokebro.kink',
  );
}
